version: "3"
services:
  app:
    container_name: node-server
    restart: always
    build: .
    ports: 
      - '5050:5050'
    links: 
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports: 
      - '27017:27017'
